---
abstract: 'pool of Test::mysqld-s reused while testing'
author:
  - 'Masakazu Ohtsuka <o.masakazu@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prove-Plugin-MySQLPool
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Prove: 0
  Cache::FastMmap: 0
  File::Temp: 0
  Mouse: 0
  POSIX::AtFork: 0
  Test::mysqld: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mash/App-Prove-Plugin-MySQLPool.git
version: 0.02
